# fly.toml app configuration file generated for chatbot-lab on 2023-05-22T13:20:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatbot-lab"
primary_region = "bog"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  OPENAI_API_KEY = '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'
  DATA_PATH = 'dataPDF'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
kill_signal = "SIGINT"
kill_timeout = 5